import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>dba – NextJS Initial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="w-screen h-screen flex justify-center items-center">
            <h1 className="text-3xl font-bold">
                dba – NextJS Initial
            </h1>
        </main>
    </>
  )
}

export default Home